
package Klient;


import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


public class KlientWisielec extends javax.swing.JFrame {
    private PrintWriter out; // Do wysyłania wiadomości do serwera
    private BufferedReader in; // Do odbierania wiadomości od serwera
    private Socket socket; 
    private PanelWisielca rysWisielca = new PanelWisielca(6);
    private JLabel[] slowoLabels;
    String nazwaKlienta;
     private volatile boolean isClosing = false; 
   
    public KlientWisielec(String serverAddress, int port) throws IOException {
        
        initComponents();
      
        rysWisielca.revalidate();
        rysWisielca.repaint();
        
        messageArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                scrollToBottom();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                scrollToBottom();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                scrollToBottom();
            }
            private void scrollToBottom() {
                messageArea.setCaretPosition(messageArea.getDocument().getLength());
            }
        });

        try {
            socket = new Socket(serverAddress, port);
            out = new PrintWriter(new BufferedWriter(new OutputStreamWriter(socket.getOutputStream())), true);
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            // Wątek do nasłuchiwania wiadomości od serwera
            new Thread(() -> {
                try {
                    String line;
                    while ((line = in.readLine()) != null && !isClosing) {
                        odbierzWiadomosc(line);
                    }
                } catch (IOException ex) {
                    if (!isClosing) {
                        messageArea.append("Rozłączono od serwera.\n");
                    }
                }
            }).start();
        } catch (IOException e) {
            messageArea.append("Nie można połączyć się z serwerem.\n");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        nowaGraButton = new javax.swing.JButton();
        zakonczGrebutton = new javax.swing.JButton();
        wisielecPane = rysWisielca;
        jLabelProby = new javax.swing.JLabel();
        slowoPanel = new javax.swing.JPanel();
        panelLiter = new javax.swing.JPanel();
        aButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        fButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        hButton = new javax.swing.JButton();
        iButton = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        kButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        mButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        oButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        qButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        sButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        uButton = new javax.swing.JButton();
        vButton = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        yButton = new javax.swing.JButton();
        zButton = new javax.swing.JButton();
        Oprojekcie = new javax.swing.JButton();
        inputField = new javax.swing.JTextField();
        wyslijButton = new javax.swing.JButton();
        graczNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gra Wisielec");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setName("klientWisielecframe"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        messageArea.setEditable(false);
        messageArea.setBackground(new java.awt.Color(255, 255, 255));
        messageArea.setColumns(20);
        messageArea.setLineWrap(true);
        messageArea.setRows(5);
        messageArea.setWrapStyleWord(true);
        messageArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        messageArea.setOpaque(false);
        messageArea.setVerifyInputWhenFocusTarget(false);
        scrollPane.setViewportView(messageArea);

        nowaGraButton.setBackground(new java.awt.Color(153, 255, 153));
        nowaGraButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nowaGraButton.setText("Nowa Gra");
        nowaGraButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nowaGraButton.setPreferredSize(new java.awt.Dimension(100, 23));
        nowaGraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowaGraButtonActionPerformed(evt);
            }
        });

        zakonczGrebutton.setBackground(new java.awt.Color(153, 255, 153));
        zakonczGrebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        zakonczGrebutton.setText("Zakończ Grę");
        zakonczGrebutton.setPreferredSize(new java.awt.Dimension(100, 23));
        zakonczGrebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zakonczGrebuttonActionPerformed(evt);
            }
        });

        wisielecPane.setBackground(new java.awt.Color(255, 255, 255));
        wisielecPane.setMinimumSize(new java.awt.Dimension(338, 423));
        wisielecPane.setPreferredSize(new java.awt.Dimension(338, 423));
        wisielecPane.setLayout(new java.awt.GridBagLayout());

        jLabelProby.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jLabelProby.setText("Pozostałe próby: 6");

        slowoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        slowoPanel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        slowoPanel.setMinimumSize(new java.awt.Dimension(654, 208));
        slowoPanel.setLayout(new java.awt.GridBagLayout());

        panelLiter.setLayout(new java.awt.GridLayout(4, 8));

        aButton.setText("A");
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });
        panelLiter.add(aButton);

        bButton.setText("B");
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });
        panelLiter.add(bButton);

        cButton.setText("C");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });
        panelLiter.add(cButton);

        dButton.setText("D");
        dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dButtonActionPerformed(evt);
            }
        });
        panelLiter.add(dButton);

        eButton.setText("E");
        eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });
        panelLiter.add(eButton);

        fButton.setText("F");
        fButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonActionPerformed(evt);
            }
        });
        panelLiter.add(fButton);

        gButton.setText("G");
        gButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gButtonActionPerformed(evt);
            }
        });
        panelLiter.add(gButton);

        hButton.setText("H");
        hButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hButtonActionPerformed(evt);
            }
        });
        panelLiter.add(hButton);

        iButton.setText("I");
        iButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iButtonActionPerformed(evt);
            }
        });
        panelLiter.add(iButton);

        jButton.setText("J");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        panelLiter.add(jButton);

        kButton.setText("K");
        kButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonActionPerformed(evt);
            }
        });
        panelLiter.add(kButton);

        lButton.setText("L");
        lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });
        panelLiter.add(lButton);

        mButton.setText("M");
        mButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonActionPerformed(evt);
            }
        });
        panelLiter.add(mButton);

        nButton.setText("N");
        nButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nButtonActionPerformed(evt);
            }
        });
        panelLiter.add(nButton);

        oButton.setText("O");
        oButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oButtonActionPerformed(evt);
            }
        });
        panelLiter.add(oButton);

        pButton.setText("P");
        pButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonActionPerformed(evt);
            }
        });
        panelLiter.add(pButton);

        qButton.setText("Q");
        qButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qButtonActionPerformed(evt);
            }
        });
        panelLiter.add(qButton);

        rButton.setText("R");
        rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonActionPerformed(evt);
            }
        });
        panelLiter.add(rButton);

        sButton.setText("S");
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });
        panelLiter.add(sButton);

        tButton.setText("T");
        tButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonActionPerformed(evt);
            }
        });
        panelLiter.add(tButton);

        uButton.setText("U");
        uButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uButtonActionPerformed(evt);
            }
        });
        panelLiter.add(uButton);

        vButton.setText("V");
        vButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonActionPerformed(evt);
            }
        });
        panelLiter.add(vButton);

        wButton.setText("W");
        wButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wButtonActionPerformed(evt);
            }
        });
        panelLiter.add(wButton);

        xButton.setText("X");
        xButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButtonActionPerformed(evt);
            }
        });
        panelLiter.add(xButton);

        yButton.setText("Y");
        yButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yButtonActionPerformed(evt);
            }
        });
        panelLiter.add(yButton);

        zButton.setText("Z");
        zButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zButtonActionPerformed(evt);
            }
        });
        panelLiter.add(zButton);

        Oprojekcie.setBackground(new java.awt.Color(255, 51, 255));
        Oprojekcie.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        Oprojekcie.setText("O Projekcie");
        Oprojekcie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OprojekcieActionPerformed(evt);
            }
        });
        panelLiter.add(Oprojekcie);

        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });

        wyslijButton.setBackground(new java.awt.Color(153, 255, 153));
        wyslijButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        wyslijButton.setText("Wyślij");
        wyslijButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        wyslijButton.setMaximumSize(new java.awt.Dimension(95, 23));
        wyslijButton.setMinimumSize(new java.awt.Dimension(95, 23));
        wyslijButton.setPreferredSize(new java.awt.Dimension(100, 23));
        wyslijButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyslijButtonActionPerformed(evt);
            }
        });

        graczNameLabel.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        graczNameLabel.setText("Nazwa gracza:");
        graczNameLabel.setMaximumSize(new java.awt.Dimension(100, 25));
        graczNameLabel.setMinimumSize(new java.awt.Dimension(100, 25));
        graczNameLabel.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(zakonczGrebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(nowaGraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(wyslijButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(wisielecPane, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(graczNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelProby, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(slowoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wyslijButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nowaGraButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zakonczGrebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(graczNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slowoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(wisielecPane, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLiter, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        wyslijWiadomosc("a");   // TODO add your handling code here:
    }//GEN-LAST:event_aButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
       wyslijWiadomosc("b");  // TODO add your handling code here:
    }//GEN-LAST:event_bButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
      wyslijWiadomosc("c");   // TODO add your handling code here:
    }//GEN-LAST:event_cButtonActionPerformed

    private void dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dButtonActionPerformed
       wyslijWiadomosc("d");  // TODO add your handling code here:
    }//GEN-LAST:event_dButtonActionPerformed

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
       wyslijWiadomosc("e");  // TODO add your handling code here:
    }//GEN-LAST:event_eButtonActionPerformed

    private void fButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonActionPerformed
        wyslijWiadomosc("f"); // TODO add your handling code here:
    }//GEN-LAST:event_fButtonActionPerformed

    private void gButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gButtonActionPerformed
       wyslijWiadomosc("g");  // TODO add your handling code here:
    }//GEN-LAST:event_gButtonActionPerformed

    private void hButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hButtonActionPerformed
      wyslijWiadomosc("h");   // TODO add your handling code here:
    }//GEN-LAST:event_hButtonActionPerformed

    private void iButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iButtonActionPerformed
         wyslijWiadomosc("i");// TODO add your handling code here:
    }//GEN-LAST:event_iButtonActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
     wyslijWiadomosc("j");    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActionPerformed

    private void kButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonActionPerformed
      wyslijWiadomosc("k");   // TODO add your handling code here:
    }//GEN-LAST:event_kButtonActionPerformed

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lButtonActionPerformed
       wyslijWiadomosc("l");  // TODO add your handling code here:
    }//GEN-LAST:event_lButtonActionPerformed

    private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonActionPerformed
       wyslijWiadomosc("m");  // TODO add your handling code here:
    }//GEN-LAST:event_mButtonActionPerformed

    private void nButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nButtonActionPerformed
      wyslijWiadomosc("n");   // TODO add your handling code here:
    }//GEN-LAST:event_nButtonActionPerformed

    private void oButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oButtonActionPerformed
       wyslijWiadomosc("o");  // TODO add your handling code here:
    }//GEN-LAST:event_oButtonActionPerformed

    private void pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonActionPerformed
        wyslijWiadomosc("p"); // TODO add your handling code here:
    }//GEN-LAST:event_pButtonActionPerformed

    private void rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonActionPerformed
       wyslijWiadomosc("r");  // TODO add your handling code here:
    }//GEN-LAST:event_rButtonActionPerformed

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
      wyslijWiadomosc("s");   // TODO add your handling code here:
    }//GEN-LAST:event_sButtonActionPerformed

    private void tButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonActionPerformed
        wyslijWiadomosc("t"); // TODO add your handling code here:
    }//GEN-LAST:event_tButtonActionPerformed

    private void uButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uButtonActionPerformed
       wyslijWiadomosc("u");  // TODO add your handling code here:
    }//GEN-LAST:event_uButtonActionPerformed

    private void wButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wButtonActionPerformed
       wyslijWiadomosc("w");  // TODO add your handling code here:
    }//GEN-LAST:event_wButtonActionPerformed

    private void yButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yButtonActionPerformed
       wyslijWiadomosc("y");  // TODO add your handling code here:
    }//GEN-LAST:event_yButtonActionPerformed

    private void zButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zButtonActionPerformed
        wyslijWiadomosc("z"); // TODO add your handling code here:
    }//GEN-LAST:event_zButtonActionPerformed

    private void qButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qButtonActionPerformed
       wyslijWiadomosc("q");  // TODO add your handling code here:
    }//GEN-LAST:event_qButtonActionPerformed

    private void vButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonActionPerformed
       wyslijWiadomosc("v");  // TODO add your handling code here:
    }//GEN-LAST:event_vButtonActionPerformed

    private void xButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButtonActionPerformed
         wyslijWiadomosc("x");  // TODO add your handling code here:
    }//GEN-LAST:event_xButtonActionPerformed

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        wyslijWiadomosc(inputField.getText().trim());      // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed

    private void wyslijButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyslijButtonActionPerformed
        wyslijWiadomosc(inputField.getText().trim());   // TODO add your handling code here:
    }//GEN-LAST:event_wyslijButtonActionPerformed

    private void nowaGraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowaGraButtonActionPerformed
   rozpocznijNowaGre();        // TODO add your handling code here:
    }//GEN-LAST:event_nowaGraButtonActionPerformed

    private void zakonczGrebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zakonczGrebuttonActionPerformed
   zakoncz();
    }//GEN-LAST:event_zakonczGrebuttonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    zakoncz(); // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    zakoncz();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void OprojekcieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OprojekcieActionPerformed
        Object response = "Kamila Wichowska: 100% udziału, ocena 17/20PKT";
        JOptionPane.showMessageDialog(this, response, "O projekcie", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_OprojekcieActionPerformed
  
    private void zakoncz() {
        isClosing = true;
        try {
            if (out != null) {
                out.println("WYLOGUJ"); // Wysłanie wiadomości do serwera o wylogowaniu
                out.flush();
                out.close();
            }
            if (in != null) {
                in.close();
            }
            if (socket != null && !socket.isClosed()) {
                socket.close();
            }
        } catch (IOException e) {
        }
        System.exit(0);
    }    
    
    private void wyslijWiadomosc(String wiadomosc) {
    if (!wiadomosc.isEmpty()) {
        if (wiadomosc.length()==1 && Character.isLetter(wiadomosc.charAt(0))){
            out.println(wiadomosc.toLowerCase());
        }else {
            out.println(wiadomosc);
        }
        inputField.setText("");
    }
    
}
  private void odbierzWiadomosc(String wiadomosc) {
    
     if (wiadomosc.startsWith("Pozostałe próby: ")) {
        int proby = Integer.parseInt(wiadomosc.substring(17));
        rysWisielca.setProby(proby);
        zaktualizujLabelProby(proby);
    } else  if(wiadomosc.startsWith("Słowo: ")){
         String slowo = wiadomosc.substring(7).toLowerCase();
         zaktualizujSlowoPanel(slowo);
     } else if ( wiadomosc.startsWith("Nazwa gracza: ")) {
         nazwaKlienta = wiadomosc.substring(13);
        zaktualizujNazweGracza(nazwaKlienta);
     }else    {
        messageArea.append(wiadomosc + "\n");
      
}}
private void zaktualizujNazweGracza(String nazwaKlienta){
     SwingUtilities.invokeLater(() -> {
         graczNameLabel.setText("Nazwa Gracza: " + nazwaKlienta);
         graczNameLabel.revalidate();
         graczNameLabel.repaint();
     });
}
private void zaktualizujSlowoPanel(String slowo) {
        SwingUtilities.invokeLater(() -> {
            slowoPanel.removeAll();
            
            slowoLabels = new JLabel[slowo.length()];
            for (int i = 0; i < slowo.length(); i++) {
                slowoLabels[i] = new JLabel(String.valueOf(slowo.charAt(i)));
                slowoLabels[i].setFont(new Font("Arial", Font.PLAIN, 40));
                slowoLabels[i].setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 10));
                slowoPanel.add(slowoLabels[i]);
            }
            slowoPanel.revalidate();
            slowoPanel.repaint();
        });
    }
  
  private void zaktualizujLabelProby(int proby) {
    SwingUtilities.invokeLater(() -> {
        jLabelProby.setText("Pozostałe próby: " + proby);
    });
}
  private void rozpocznijNowaGre() {
        rysWisielca.setProby(6);
        zaktualizujLabelProby(6);
        slowoPanel.removeAll();
        slowoPanel.revalidate();
        slowoPanel.repaint();
        messageArea.setText("");
        out.println("NOWA_GRA");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlientWisielec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlientWisielec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlientWisielec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlientWisielec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new KlientWisielec("localhost", 12345).setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(KlientWisielec.class.getName()).log(Level.SEVERE, null, ex);
            }
       

        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Oprojekcie;
    private javax.swing.JButton aButton;
    private javax.swing.JButton bButton;
    private javax.swing.JButton cButton;
    private javax.swing.JButton dButton;
    private javax.swing.JButton eButton;
    private javax.swing.JButton fButton;
    private javax.swing.JButton gButton;
    private javax.swing.JLabel graczNameLabel;
    private javax.swing.JButton hButton;
    private javax.swing.JButton iButton;
    private javax.swing.JTextField inputField;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabelProby;
    private javax.swing.JButton kButton;
    private javax.swing.JButton lButton;
    private javax.swing.JButton mButton;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JButton nButton;
    private javax.swing.JButton nowaGraButton;
    private javax.swing.JButton oButton;
    private javax.swing.JButton pButton;
    private javax.swing.JPanel panelLiter;
    private javax.swing.JButton qButton;
    private javax.swing.JButton rButton;
    private javax.swing.JButton sButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel slowoPanel;
    private javax.swing.JButton tButton;
    private javax.swing.JButton uButton;
    private javax.swing.JButton vButton;
    private javax.swing.JButton wButton;
    private javax.swing.JPanel wisielecPane;
    private javax.swing.JButton wyslijButton;
    private javax.swing.JButton xButton;
    private javax.swing.JButton yButton;
    private javax.swing.JButton zButton;
    private javax.swing.JButton zakonczGrebutton;
    // End of variables declaration//GEN-END:variables
}
